import { useState, useEffect ,useRef} from 'react'
import { useParams } from 'react-router-dom'
import api from '../services/api'
import ModuleQuiz from './ModuleQuiz'

function CoursePage() {
  const { id } = useParams()

  // All modules available inside the course
  const [modules, setModules] = useState([])

  // ONLY modules generated by AI roadmap
  const [roadmapModules, setRoadmapModules] = useState([])

  const [course, setCourse] = useState(null)
  const [assessment, setAssessment] = useState(null)
  const [progress, setProgress] = useState(null)

  const [loading, setLoading] = useState(true)
  const [marking, setMarking] = useState(false)

  // Actual course module currently being viewed
  const [activeModule, setActiveModule] = useState(null)

  const [error, setError] = useState('')

  const [videoDuration, setVideoDuration] = useState(0)
  const [currentTime, setCurrentTime] = useState(0)
  const [watchInterval, setWatchInterval] = useState(null)

  const token = localStorage.getItem('token')

  // =========================================================
  // FIND ACTUAL COURSE MODULE FROM AI ROADMAP MODULE
  // =========================================================
  const getCourseModuleForRoadmap = (roadmapModule) => {
    if (!roadmapModule || !modules.length) {
      return null
    }

    const topic = roadmapModule.topic?.toLowerCase().trim()
    const level = roadmapModule.level?.toLowerCase().trim()

    if (!topic) {
      return null
    }

    // ---------------------------------------------------------
    // First try:
    // topic + difficulty exact match
    // ---------------------------------------------------------
    const exactMatch = modules.find((module) => {
      const moduleTitle = module.title?.toLowerCase().trim() || ''
      const moduleSkill = module.skillTag?.toLowerCase().trim() || ''
      const moduleDifficulty =
        module.difficulty?.toLowerCase().trim() || ''

      const topicMatches =
        moduleSkill === topic ||
        moduleTitle === topic ||
        moduleTitle.includes(topic)

      const levelMatches =
        moduleDifficulty === level

      return topicMatches && levelMatches
    })

    if (exactMatch) {
      return exactMatch
    }

    // ---------------------------------------------------------
    // Second try:
    // topic only
    //
    // This is useful when AI says:
    // React beginner
    //
    // but your actual course has:
    // React Fundamentals
    // ---------------------------------------------------------
    const topicMatch = modules.find((module) => {
      const moduleTitle = module.title?.toLowerCase().trim() || ''
      const moduleSkill = module.skillTag?.toLowerCase().trim() || ''

      return (
        moduleSkill === topic ||
        moduleTitle === topic ||
        moduleTitle.includes(topic)
      )
    })

    return topicMatch || null
  }

  // =========================================================
  // LOAD COURSE + PROGRESS + ASSESSMENT + ROADMAP
  // =========================================================
  useEffect(() => {
    const fetchData = async () => {
      try {
        setLoading(true)
        setError('')

        const [
          courseRes,
          progressRes,
          assessmentRes,
          roadmapRes
        ] = await Promise.all([
          // Course and ALL available modules
          api.get(`/courses/${id}`, {
            headers: {
              Authorization: `Bearer ${token}`
            }
          }),

          // User progress
          api.get(`/progress/${id}`, {
            headers: {
              Authorization: `Bearer ${token}`
            }
          }),

          // Assessment questions
          api.get(`/assessment/course/${id}/questions`, {
            headers: {
              Authorization: `Bearer ${token}`
            }
          }),

          // AI generated roadmap
          // CoursePage.jsx, line ~134
            api.get(`/roadmap?courseId=${id}`, {
              headers: { Authorization: `Bearer ${token}` }
            })
          
        ])

        // =====================================================
        // COURSE DATA
        // =====================================================

        const courseData = courseRes.data.course
        const courseModules = courseRes.data.modules || []

        setCourse(courseData)

        // Keep ALL course modules internally.
        // These are needed to find the actual video/module.
        setModules(courseModules)

        // =====================================================
        // PROGRESS
        // =====================================================

        setProgress(progressRes.data)

        // =====================================================
        // ASSESSMENT
        // =====================================================

        setAssessment(
          assessmentRes.data.questions || []
        )

        // AI ROADMAP

        const generatedRoadmap =
          roadmapRes.data.roadmap?.modules || []

        console.log(
          'AI ROADMAP MODULES:',
          generatedRoadmap
        )

        setRoadmapModules(generatedRoadmap)

        // SELECT FIRST ROADMAP MODULE
      const urlParams = new URLSearchParams(window.location.search)
      const skillFromUrl = urlParams.get('skill')

      if (generatedRoadmap.length > 0 || skillFromUrl) {
        // prefer the topic the user actually clicked; fall back to the first roadmap module
        const targetTopic = skillFromUrl || generatedRoadmap[0]?.topic

        const actualModule = courseModules.find((module) => {
          const topic = targetTopic?.toLowerCase().trim()
          const moduleTitle = module.title?.toLowerCase().trim() || ''
          const moduleSkill = module.skillTag?.toLowerCase().trim() || ''

          return (
            moduleSkill === topic ||
            moduleTitle === topic ||
            moduleTitle.includes(topic)
          )
        })

        if (actualModule) {
          setActiveModule(actualModule)
        } else {
          console.warn('Could not find module for topic:', targetTopic)
        }
      }

      } catch (err) {
        console.error(
          'COURSE PAGE ERROR:',
          err
        )

        console.error(
          'COURSE PAGE RESPONSE:',
          err.response?.data
        )

        setError(
          err.response?.data?.message ||
          'Failed to load course'
        )
      } finally {
        setLoading(false)
      }
    }

    fetchData()
  }, [id])

  // CHECK IF MODULE IS COMPLETED
  const isCompleted = (moduleId) => {
    return progress?.completedList?.some(
      (p) =>
        p.moduleId?._id === moduleId ||
        p.moduleId === moduleId
    )
  }

  // =========================================================
  // MARK MODULE COMPLETE
  // =========================================================
  const handleMarkComplete = async () => {
    if (!activeModule) return

    setMarking(true)

    try {
      await api.post(
        '/progress/complete',
        {
          courseId: id,
          moduleId: activeModule._id
        },
        {
          headers: {
            Authorization: `Bearer ${token}`
          }
        }
      )

      // Refresh progress
      const progressRes = await api.get(
        `/progress/${id}`,
        {
          headers: {
            Authorization: `Bearer ${token}`
          }
        }
      )

      setProgress(progressRes.data)

      // -------------------------------------------------------
      // Move to NEXT ROADMAP MODULE
      // NOT next module from entire course
      // -------------------------------------------------------

      const currentRoadmapIndex =
        roadmapModules.findIndex(
          (roadmapModule) => {
            const actualModule =
              getCourseModuleForRoadmap(
                roadmapModule
              )

            return (
              actualModule?._id ===
              activeModule._id
            )
          }
        )

      const nextRoadmapIndex =
        currentRoadmapIndex + 1

      if (
        nextRoadmapIndex <
        roadmapModules.length
      ) {
        const nextRoadmapModule =
          roadmapModules[nextRoadmapIndex]

        const nextActualModule =
          getCourseModuleForRoadmap(
            nextRoadmapModule
          )

        if (nextActualModule) {
          setActiveModule(
            nextActualModule
          )
        }
      }

    } catch (err) {
      console.error(
        'MARK COMPLETE ERROR:',
        err
      )

      setError(
        err.response?.data?.message ||
        'Failed to mark complete'
      )
    } finally {
      setMarking(false)
    }
  }

  // =========================================================
  // VIDEO WATCH PROGRESS
  // =========================================================
        const currentTimeRef = useRef(0)

      // keep ref in sync with latest currentTime without retriggering the interval effect
      useEffect(() => {
        currentTimeRef.current = currentTime
      }, [currentTime])

      // Send watch progress every 10 seconds
      useEffect(() => {
        if (!activeModule || !videoDuration) {
          return
        }

        const interval = setInterval(async () => {
          const time = currentTimeRef.current

          if (time > 0 && videoDuration > 0) {
            try {
              await api.post(
                '/videos/watch-progress',
                {
                  moduleId: activeModule._id,
                  courseId: id,
                  watchedSeconds: Math.round(time),
                  totalSeconds: Math.round(videoDuration),
                  lastPosition: Math.round(time)
                },
                {
                  headers: {
                    Authorization: `Bearer ${token}`
                  }
                }
              )
            } catch (err) {
              // Do not interrupt video if tracking fails
              console.log('Watch progress error:', err.message)
            }
          }
        }, 10000)

        setWatchInterval(interval)

        // Cleanup
        return () => {
          clearInterval(interval)
        }
      }, [activeModule, videoDuration]) // currentTime removed — this is the fix

      // RESET VIDEO TIME WHEN MODULE CHANGES
      useEffect(() => {
        setVideoDuration(0)
        setCurrentTime(0)
      }, [activeModule])

  // MAIN PAGE

  return (
    <div className="min-h-screen bg-[#080808] flex">

      {/* =====================================================
          LEFT NAVIGATION
      ====================================================== */}

      <div className="w-[180px] flex-shrink-0 border-r border-white/6 flex flex-col px-5 py-6 bg-[#060606]">

        <span className="font-black text-white text-sm tracking-tight mb-8">
          B2B Learn.
        </span>

        <nav className="flex flex-col gap-1 flex-1">

          <a
            href="/dashboard"
            className="text-[10px] font-bold tracking-[1px] uppercase text-white/25 px-3 py-2 hover:text-white/50 transition-colors"
          >
            Dashboard
          </a>

          <a
            href="/dashboard"
            className="text-[10px] font-bold tracking-[1px] uppercase text-white bg-white/6 px-3 py-2 rounded-sm"
          >
            Courses
          </a>

          <a
            href="/dashboard"
            className="text-[10px] font-bold tracking-[1px] uppercase text-white/25 px-3 py-2 hover:text-white/50 transition-colors"
          >
            Profile
          </a>

        </nav>

        <a
          href="/dashboard"
          className="text-[10px] font-bold tracking-[1px] uppercase text-white/20 px-3 py-2 hover:text-white/40 transition-colors"
        >
          ← Back
        </a>

      </div>

      {/* =====================================================
          MAIN CONTENT
      ====================================================== */}

      <div className="flex-1 flex flex-col overflow-hidden">

        {/* ===================================================
            TOP BAR
        ==================================================== */}

        <div className="flex justify-between items-center px-8 py-4 border-b border-white/5">

          <div>

            <p className="text-[9px] font-bold tracking-[2px] uppercase text-white/25 mb-0.5">
              // course
            </p>

            <p className="text-white font-bold text-sm">
              {course?.title}
            </p>

          </div>

          <div className="text-right">

            <p className="text-[9px] font-bold tracking-[1.5px] uppercase text-white/25 mb-0.5">
              Progress
            </p>

            <p className="text-white font-black text-lg">
              {progress?.percentage || 0}%
            </p>

          </div>

        </div>

        {/* ===================================================
            COURSE BODY
        ==================================================== */}

        <div className="flex flex-1 overflow-hidden">

          {/* =================================================
              AI ROADMAP MODULE SIDEBAR
          ================================================== */}

          <div className="w-[240px] border-r border-white/6 overflow-y-auto px-4 py-5">

            <p className="text-[9px] font-bold tracking-[2px] uppercase text-white/25 mb-4">
              // modules
            </p>

            {/* Progress bar */}
            <div className="h-[2px] bg-white/8 rounded-sm mb-5">

              <div
                className="h-[2px] bg-white rounded-sm transition-all"
                style={{
                  width: `${progress?.percentage || 0}%`
                }}
              />

            </div>

            {/* =================================================
                ONLY AI ROADMAP MODULES ARE DISPLAYED HERE
            ================================================== */}

            <div className="flex flex-col gap-2">

              {roadmapModules.map(
                (roadmapModule, index) => {

                  // Find actual course module
                  const module =
                    getCourseModuleForRoadmap(
                      roadmapModule
                    )

                  // If AI module doesn't exist
                  // in course, don't show broken item
                  if (!module) {
                    return null
                  }

                  const done =
                    isCompleted(module._id)

                  const active =
                    activeModule?._id ===
                    module._id

                  return (
                    <button
                      key={`${module._id}-${index}`}
                      onClick={() => {
                        setActiveModule(module)
                        setError('')
                      }}
                      className={`text-left border rounded-sm px-3 py-3 transition-all ${
                        active
                          ? 'border-white/30 bg-white/4'
                          : 'border-white/6 hover:border-white/15'
                      }`}
                    >

                      {/* Difficulty */}
                      <div className="flex items-center gap-2 mb-1">

                        <div
                          className={`w-1.5 h-1.5 rounded-full flex-shrink-0 ${
                            done
                              ? 'bg-white'
                              : active
                                ? 'bg-white/60'
                                : 'bg-white/15'
                          }`}
                        />

                        <span
                          className={`text-[9px] font-bold tracking-[1px] uppercase ${
                            done
                              ? 'text-white/40'
                              : active
                                ? 'text-white'
                                : 'text-white/25'
                          }`}
                        >
                          {roadmapModule.level}
                        </span>

                      </div>

                      {/* Topic */}
                      <p
                        className={`text-xs font-bold leading-tight ${
                          done
                            ? 'text-white/35 line-through'
                            : 'text-white'
                        }`}
                      >
                        {roadmapModule.topic}
                      </p>

                      {/* Completed */}
                      {done && (
                        <p className="text-[9px] font-bold tracking-[1px] uppercase text-white/30 mt-1">
                          done
                        </p>
                      )}

                    </button>
                  )
                }
              )}

            </div>

          </div>

          {/* =================================================
              VIDEO / MODULE CONTENT
          ================================================== */}

          <div className="flex-1 overflow-y-auto px-8 py-6">

            {activeModule ? (

              <>

                {/* Module heading */}

                <p className="text-[9px] font-bold tracking-[2px] uppercase text-white/25 mb-2">
                  // {activeModule.skillTag?.toLowerCase()}
                </p>

                <h1 className="text-2xl font-black text-white tracking-tight mb-2">
                  {activeModule.title}
                </h1>

                <p className="text-sm text-white/35 mb-6 leading-relaxed">
                  {activeModule.description ||
                    'No description provided.'}
                </p>

                {/* =================================================
                    VIDEO PLAYER
                ================================================== */}

                {activeModule.contentUrl ? (

                  <div className="border border-white/8 rounded-sm mb-6 overflow-hidden bg-black">

                    <video
                      key={activeModule._id}
                      controls
                      className="w-full"
                      style={{
                        aspectRatio: '16/9'
                      }}
                      onLoadedMetadata={(e) => {
                        setVideoDuration(
                          e.target.duration
                        )
                      }}
                      onTimeUpdate={(e) => {
                        setCurrentTime(
                          e.target.currentTime
                        )
                      }}
                      controlsList="nodownload"
                    >

                      <source
                        src={activeModule.contentUrl}
                        type="video/mp4"
                      />

                      Your browser does not support
                      the video tag.

                    </video>

                  </div>

                ) : (

                  <div className="border border-white/8 rounded-sm mb-6 aspect-video flex items-center justify-center">

                    <p className="text-white/15 text-xs font-bold tracking-[2px] uppercase">
                      // no video content
                    </p>

                  </div>

                )}

                {/* =================================================
                    MODULE INFORMATION
                ================================================== */}

                <div className="grid grid-cols-3 gap-4 mb-6">

                  {/* Duration */}

                  <div className="border border-white/8 rounded-sm p-3">

                    <p className="text-[9px] font-bold tracking-[1.5px] uppercase text-white/25 mb-1">
                      Duration
                    </p>

                    <p className="text-white font-bold text-sm">
                      {activeModule.duration || '—'} min
                    </p>

                  </div>

                  {/* Difficulty */}

                  <div className="border border-white/8 rounded-sm p-3">

                    <p className="text-[9px] font-bold tracking-[1.5px] uppercase text-white/25 mb-1">
                      Difficulty
                    </p>

                    <p className="text-white font-bold text-sm capitalize">
                      {activeModule.difficulty}
                    </p>

                  </div>

                  {/* Skill */}

                  <div className="border border-white/8 rounded-sm p-3">

                    <p className="text-[9px] font-bold tracking-[1.5px] uppercase text-white/25 mb-1">
                      Skill
                    </p>

                    <p className="text-white font-bold text-sm">
                      {activeModule.skillTag}
                    </p>

                  </div>

                </div>

                {/* Error */}

                {error && (
                  <p className="text-red-400 text-xs mb-4">
                    {error}
                  </p>
                )}

                {/* =================================================
                    ACTIONS
                ================================================== */}

                <div className="flex gap-3">

                  {/* Progress */}

                  <div className="border border-white/6 rounded-sm px-4 py-3">

                    <p className="text-[9px] font-bold tracking-[2px] uppercase text-white/20 mb-1">
                      // auto tracking
                    </p>

                    <p className="text-white/30 text-xs">

                      {isCompleted(
                        activeModule._id
                      )
                        ? '✓ Module completed'
                        : 'Continue Learning'}

                    </p>

                  </div>

                  {/* =================================================
                      NEXT BUTTON
                  ================================================== */}

                  {(() => {

                    const currentRoadmapIndex =
                      roadmapModules.findIndex(
                        (roadmapModule) => {

                          const module =
                            getCourseModuleForRoadmap(
                              roadmapModule
                            )

                          return (
                            module?._id ===
                            activeModule._id
                          )
                        }
                      )

                    const hasNext =
                      currentRoadmapIndex !== -1 &&
                      currentRoadmapIndex <
                        roadmapModules.length - 1

                    if (!hasNext) {
                      return null
                    }

                    return (
                      <button
                        onClick={() => {

                          const nextRoadmapModule =
                            roadmapModules[
                              currentRoadmapIndex + 1
                            ]

                          const nextModule =
                            getCourseModuleForRoadmap(
                              nextRoadmapModule
                            )

                          if (nextModule) {
                            setActiveModule(
                              nextModule
                            )

                            setError('')
                          }

                        }}
                        className="border border-white/20 text-white/60 font-bold text-sm px-6 py-2.5 rounded-sm hover:border-white/40 transition-colors"
                      >
                        Next →
                      </button>
                    )

                  })()}

                </div>

                {/* =================================================
                    MODULE QUIZ
                ================================================== */}

                <ModuleQuiz
                  moduleId={activeModule._id}
                  courseId={id}
                />

              </>

            ) : (

              <div className="flex items-center justify-center h-full">

                <p className="text-white/20 text-xs font-bold tracking-[2px] uppercase">
                  // select a module
                </p>

              </div>

            )}

          </div>

        </div>

      </div>

    </div>
  )
}

export default CoursePage